---
abstract: 'Unicode bidi algorithm using libfribidi'
author:
  - 'Moshe Kamensky <kamensky@cpan.org>'
build_requires:
  Data::Dumper: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
  charnames: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132510'
keywords:
  - Bidi
  - RTL
  - Hebrew
  - Arabic
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Bidi
no_index:
  package:
    - Text::Bidi::private
    - Text::Bidi::privatec
provides:
  Text::Bidi:
    file: lib/Text/Bidi.pm
    version: 2.07
  Text::Bidi::Array:
    file: lib/Text/Bidi/Array.pm
    version: 2.07
  Text::Bidi::Array::Byte:
    file: lib/Text/Bidi/Array/Byte.pm
    version: 2.07
  Text::Bidi::Array::Long:
    file: lib/Text/Bidi/Array/Long.pm
    version: 2.07
  Text::Bidi::Constants:
    file: lib/Text/Bidi/Constants.pm
    version: 2.07
  Text::Bidi::Paragraph:
    file: lib/Text/Bidi/Paragraph.pm
    version: 2.07
requires:
  Carp: 0
  DynaLoader: 0
  Encode: 0
  Exporter: 0
  Getopt::Long: 0
  Tie::Array: 0
  base: 0
  integer: 0
  open: 0
  overload: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Bidi
  homepage: https://github.com/mkamensky/Text-Bidi
  repository: https://github.com/mkamensky/Text-Bidi.git
version: 2.07
